server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: parking-space-service
          uri: lb://PARKING-SPACE-SERVICE
          predicates:
            - Path=/parking_space_service/**

        - id: User-Service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user_service/**

        - id: Vehicle-Service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle_service/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment_service/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
